version: '3'

services:
    nginx:
        image: nginx:1.18.0-alpine
        container_name: nginx
        volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8902:8902"
            - "8904:8904"
    meta1:
        build:
            context: ./images/cnosdb-meta/
            dockerfile: ./${TYPE}/Dockerfile
            args:
                CNOSDB_META_TAG: ${CNOSDB_META_TAG}
        image: "cnosdb/cnosdb-meta"
        container_name: meta1.cnosdb.com
        volumes:
            - ./etc/meta1/cnosdb-meta.conf:/etc/cnosdb/cnosdb-meta.conf
            - ./var/lib/meta1:/var/lib/cnosdb
        command:
            - /bin/bash
            - -c
            - |
                cnosdb-meta --config /etc/cnosdb/cnosdb-meta.conf
    meta2:
        build:
            context: ./images/cnosdb-meta/
            dockerfile: ./${TYPE}/Dockerfile
            args:
                CNOSDB_META_TAG: ${CNOSDB_META_TAG}
        image: "cnosdb/cnosdb-meta"
        container_name: meta2.cnosdb.com
        volumes:
            - ./etc/meta2/cnosdb-meta.conf:/etc/cnosdb/cnosdb-meta.conf
            - ./var/lib/meta2:/var/lib/cnosdb
        command:
            - /bin/bash
            - -c
            - |
                cnosdb-meta --config /etc/cnosdb/cnosdb-meta.conf
    meta3:
        build:
            context: ./images/cnosdb-meta/
            dockerfile: ./${TYPE}/Dockerfile
            args:
                CNOSDB_META_TAG: ${CNOSDB_META_TAG}
        image: "cnosdb/cnosdb-meta"
        container_name: meta3.cnosdb.com
        volumes:
            - ./etc/meta3/cnosdb-meta.conf:/etc/cnosdb/cnosdb-meta.conf
            - ./var/lib/meta3:/var/lib/cnosdb
        command:
            - /bin/bash
            - -c
            - |
                cnosdb-meta --config /etc/cnosdb/cnosdb-meta.conf
    query_tskv1:
        build:
            context: ./images/cnosdb/
            dockerfile: ./${TYPE}/Dockerfile
            args:
                CNOSDB_TAG: ${CNOSDB_TAG}
        image: "cnosdb/cnosdb"
        container_name: query_tskv1.cnosdb.com
        volumes:
            - ./etc/query_tskv1:/etc/cnosdb
            - ./var/lib/query_tskv1:/var/lib/cnosdb
        command:
            - /bin/bash
            - -c
            - |
                cnosdb run --config /etc/cnosdb/cnosdb.conf
    query_tskv2:
        build:
            context: ./images/cnosdb/
            dockerfile: ./${TYPE}/Dockerfile
            args:
                CNOSDB_TAG: ${CNOSDB_TAG}
        image: "cnosdb/cnosdb"
        container_name: query_tskv2.cnosdb.com
        volumes:
            - ./etc/query_tskv2:/etc/cnosdb
            - ./var/lib/query_tskv2:/var/lib/cnosdb
        command:
            - /bin/bash
            - -c
            - |
                cnosdb run --config /etc/cnosdb/cnosdb.conf
